// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar_SA = {
  "Main": {
    "Title": "Beatrice",
    "English": "English",
    "Arabic": "العربية",
    "LanguageTransformation": "English",
    "TryAgain": "حاول مرة اخرى",
    "reset_locale": "إعادة تعيين اللغة المحفوظة",
    "Accept": "قبول",
    "Cancel": "الغاء",
    "Delete": "مسح",
    "Reject": "رفض",
    "Gallery": "الاستدوديو",
    "Camera": "الكاميرا",
    "Send": "إرسال",
    "Search": "البحث",
    "CheckInternetConnection": "تأكد من الاتصال بالانترنت",
    "Loading": "جارى التحميل ٫٫٫",
    "noConnection": "لا يوجد اتصال ب الانترنت",
    "boorConnection": "الانترنت ضعيف",
    "serverError": "مشكلة بالسيرفر حاول مره اخرى"
  },
  "Search": {
    "WriteYourSearchKeyWordHere": "اكتب كلمة البحث هنا",
    "SearchHere": "ابحث هنا",
    "Search": "بحث",
    "ChooseCategory": "اختر القسم الرئيسى",
    "ChooseSubcategory": "اختر القسم الفرعى",
    "NoSearchDataFound": "لا توجد نتائج بحث"
  },
  "Drawer": {
    "AppWelcomesYou": "تطبيق linkerhub يرحب بك",
    "PersonalData": "الملف الشخصي",
    "AddAd": "اضافه اعلان",
    "MyAds": "إعلاناتي",
    "Binders": "الموثقين",
    "AppAgency": "توكيل التطبيق",
    "RentContract": "عقود الإيجار",
    "PushQuest": "دفع السعي",
    "CustomerService": "خدمة العملاء",
    "ShareApp": "مشاركة التطبيق"
  },
  "Orders": {
    "OrderAddress": "عنوان الطلب",
    "ConfirmOrder": "تأكيد الطلب",
    "Description": "الوصف",
    "ReceiptLocation": "موقع الاستلام",
    "DeliveryLocation": "موقع التسليم",
    "OrderLocation": "عنوان الطلب",
    "Current": "الحالية",
    "CurrentOrders": "الطلبات الحالية",
    "ConfirmedOrders": "الطلبات المؤكدة والمنفذة",
    "InProgress": "قيد التفيذ",
    "Finished": "السابقة",
    "AcceptAndSendPriceOffer": "قبول وإرسال عرض سعر",
    "EnterRequiredPriceToConfirmService": "أدخل السعر المطلوب لتقديم الخدمة",
    "Products": "المنتجات",
    "Services": "الخدمات",
    "ShippingAddress": "عنوان الشحن",
    "OrderStatus": "حالة الطلب",
    "OrderInfo": "معلومات الطلب",
    "AddOrder": "إضافة طلب",
    "ChooseTargetAdvertiserCategory": "إختر فئة المعلن المستهدف",
    "TargetAdvertiserCategory": "فئة الإعلان المستهدف",
    "CreateNewRequestForm": "إنشاء نموذج طلب جديد",
    "ItemOrProductDescription": "وصف السلعة/المنتج/الخدمة",
    "RequiredAdDate": "تاريخ الإعلان المطلوب",
    "AdResidence": "مقر الإعلان",
    "AdDuration": "مدة الإعلان بالدقيقة",
    "AdVia": "الإعلان عبر",
    "OpenedOrder": "الطلب مفتوح",
    "ConfirmedOrder": "الطلب مؤكد",
    "ShowOrder": "عرض الطلب",
    "CancelOrder": "إلغاء الطلب",
    "MyCurrentOrder": "طلباتي الحالية",
    "MyConfirmedOrder": "طلباتي المؤكدة والمنفذة",
    "OrderProviderInfo": "بيانات مقدم الطلب",
    "RejectOrder": "إلغاء الطلب"
  },
  "Offers": {
    "OfferDetails": "تفاصيل العرض",
    "Offers": "العروض",
    "Title": "العنوان",
    "StartDate": "تاريخ البداية",
    "EndDate": "تاريح النهاية",
    "Code": "الكود",
    "OfferUsed": "العرض المستخدم",
    "MaximumNumberUfUse": "الحد الأقصى لعدد الإستخدام",
    "AddOffer": "أضافة عرض",
    "EditOffer": "تعديل العرض",
    "UploadOfferPhoto": "رفع صورة العرض",
    "MaximumNumberOfUse": "الحد الأقصى لعدد الإستخدام",
    "OfferFees": "رسوم العرض",
    "Add": "إضافة",
    "Discount": "خصم",
    "Clear": "مسح",
    "InActive": "غير مفعل",
    "Edit": "تعديل",
    "AreYouSureAboutReactiveThisOffer": "هل أنت متأكد من إعادة تفعيل هذا العرض؟",
    "YouHaveToWaitAdminApproval": "عليك أن تنتظر موافقة المسؤول",
    "PaymentSuccessfully": "تم الدفع بنجاح",
    "FeesAreNonRefundable": "الرسوم غير قابلة للاسترداد",
    "AreYouSureAboutDeactivateThisOffer": "هل أنت متأكد من إلغاء تنشيط هذا العرض؟",
    "DeActivate": "إلغاء تنشيط",
    "Cancel": "إلغاء"
  },
  "Home": {
    "OrdersFromManagement": "الطلبات المسنده من الاداره",
    "NewOrder": "طلب جديد",
    "OrderNumber": "طلب رقم",
    "ClientName": "اسم العميل",
    "OrderTime": "وقت الزياره",
    "More": "المزيد",
    "ServicesCategories": "اقسام الخدمات",
    "ProductsCategories": "اقسام المنتجات",
    "BestProducts": "افضل المنتجات"
  },
  "AddProduct": {
    "ProductImages": "صور المنتج",
    "ProductAddedSuccessfully": "تم اضافة المنتج بنجاح",
    "ProductEditedSuccessfully": "تم تعديل المنتج بنجاح",
    "SaveEdits": "حفظ التعديلات",
    "ProductName": "اسم المنتج",
    "Category": "القسم الرئيسى",
    "SubCategory": "القسم الفرعى",
    "ShortDescription": "وصف قصير عن القسم",
    "SpecialAdditions": "اضافات خاصة",
    "AdditionPrice": "سعر الاضافة",
    "AddProduct": "اضافة منتج",
    "Add": "اضافة",
    "EditProduct": "تعديل المنتج"
  },
  "Idea": {
    "AddIdea": "اضافة فكره",
    "EditIdea": "تعديل فكره",
    "IdeaAddress": "عنوان الفكره",
    "IdeaDesc": "وصف الفكره",
    "IdeaDuration": "مدة عرض الفكره",
    "Add": "اضافة",
    "Edit": "تعديل المنتج",
    "YouMustPutExplanationToAvoidTheft": "يرجي وضع شرح يضمن عدم سرقه الفكره منك",
    "ValidateIdeaAddress": "عنوان الفكره مطلوب",
    "ValidateIdeaImages": "صور الفكره مطلوبه",
    "ValidateIdeaDuration": "وقت عرض الفكره مطلوب",
    "MyIdeas": "أفكارى"
  },
  "BottomNavigation": {
    "Language": "اللغة",
    "Notifications": "الإشعارات",
    "Home": "الرئيسية",
    "Conversations": "الرسائل",
    "MyOrders": "طلباتى",
    "Profile": "حسابي",
    "More": "المزيد",
    "Messages": "الرسائل",
    "DoYouWantCloseApp": "هل تريد اغلاق التطبيق",
    "Yes": "نعم",
    "No": "لا"
  },
  "More": {
    "PersonalData": "الملف الشخصى",
    "ChangeLanguage": "تغيير اللغة",
    "Wallet": "المحفظة",
    "PaymentWays": "طرق الدفع",
    "UsingPolicy": "سياسة الإستخدام",
    "TermsAndConditions": "الشروط والأحكام",
    "ShareApp": "مشاركة التطبيق",
    "ContactUs": "التواصل معنا",
    "AboutApp": "عن التطبيق",
    "Terms": "الشروط والأحكام",
    "Policy": "سياسة الخصوصية",
    "AddYourAd": "أضف اعلانك",
    "MyAds": "اعلاناتى",
    "AddAuction": "اضافة مزاد",
    "MyAuctions": "مزاداتى",
    "Favourite": "المفضلة",
    "BonusPoints": "نقاط البونص",
    "LogOut": "تسجيل الخروج",
    "Evaluations": "التقيمات",
    "HealthCertificate": "الشهاده الصحيه",
    "DeliveryAndReceiveChild": "تسليم واستلام الطفل",
    "MandateDeliveryAndReceive": "تفويض تسليم واستلام",
    "CallUs": "اتصل بنا",
    "QrCode": "كود التعريف الشخصى",
    "Settings": "الإعدادات",
    "Reviews": "التقييمات",
    "Save": "حفظ"
  },
  "ReserveConfirmation": {
    "ReserveConfirmation": "إتمام الحجز",
    "ChildInfo": "معلومات الطفل",
    "Living": "السكن",
    "Attachments": "المرفقات",
    "ChildName": "اسم الطفل",
    "InPocoParentis": "ولى الأمر",
    "inPocoParentisName": "اسم ولى الأمر",
    "Gender": "الجنس",
    "Male": "ذكر",
    "FeMale": "أنثى",
    "DateOfBirth": "تاريخ الميلاد",
    "BirthPlace": "مكان الميلاد",
    "NumberOfBrothersAndSisters": "عدد الأخوه والأخوات",
    "ChildRankBetweenBrotherHood": "ترتيب الطفل بين أخوته",
    "BabyNameQuadruple": "اسم الطفل رباعى",
    "InPocoParentisMobile": "رقم جوال ولى الأمر",
    "Kinship": "صلة القرابة",
    "EducationQualification": "المؤهل التعليمي",
    "JobTitle": "المسمى الوظيفى",
    "Workplace": "مكان العمل",
    "WorkPhone": "هاتف العمل",
    "ClientResidence": "محل اقامه الطفل",
    "MainRoadNameAndBuildingNumber": "اسم الشارع الرئيسي-رقم المبنى",
    "NationalAddress": "العنوان الوطني",
    "Next": "التالي",
    "FamilyCardPhoto": "صورة بطاقه العائلة",
    "BirthCertificatePicture": "صورة شهاده الميلاد",
    "ChildProfilePicture": "صورة شخصية للطفل",
    "HealthCertificatePictures": "صورة الشهادة الصحية",
    "VaccinationCertificatePictures": "صورة شهاة التطعيم",
    "UploadMedicalCertificate": "رفع الشهاده الصحيه",
    "UploadMedicalInsuranceCertificate": "رفع شهاده التأمين الطبى",
    "NotRequiredIfAvailable": "( غير اجباريه ان وجد )",
    "UploadVaccinationCertificate": "رفع شهاده التطعيم",
    "RenewVia6Months": "تجدد لمده 6 شهور",
    "HealthCertificate": "الشهاده الصحيه"
  },
  "OrderDetails": {
    "ServiceConfirmed": "تم تنفيذ الخدمة",
    "OrderNumber": "طلب رقم",
    "OrderDetails": "تفاصيل الطلب",
    "AcceptOrder": "قبول الطلب",
    "RejectOrder": "إلغاء الطلب",
    "FinishOrder": "انهاء الطلب",
    "ContactWithCustomer": "تواصل مع العميل",
    "Products": "المنتجات",
    "NotesFromClient": "ملاحظات من العميل",
    "AddressDetails": "تفاصيل العنوان",
    "OrderSummary": "ملخص الطلب",
    "AdditionalTax": "القيمة المضافة",
    "ServicePrice": "رسوم الخدمة",
    "Total": "الاجمالى",
    "Note": "ملحوظة : الاجمالى لا يشمل سعر التوصيل",
    "Prepared": "تم تجهيز الطلب",
    "Delivered": "تم التوصيل",
    "ThanksForDelivery": "شكرا لتوصيلك الطلب",
    "YouCanFollowNewOrders": "يمكنك متابعة الطلبات الجديدة الان",
    "Orders": "الطلبات",
    "YouCanFollowOrderToConfirmDelegateArrival": "يمكنك متابعة الطلب لتأكيد وصول المندوب",
    "FollowOrder": "متابعة الطلب",
    "ServerInfo": "معلومات العامل",
    "ClientInfo": "معلومات العميل",
    "ClientLocation": "عنوان العميل",
    "TotalProducts": "مجموع المنتجات",
    "ShippingPrice": "رسوم التوصيل",
    "TaxAmount": "ضريبة مضافة",
    "ShippedProducts": "تم توصيل المنتجات",
    "ShowAll": "عرض الكل",
    "ConfirmedShippingProducts": "تم تأكيد توصيل المنتجات",
    "YouCanReceiveNewOrders": "يمكنك استقبال طلبات جديده الان",
    "Home": "الرئيسية",
    "OrderDate": "تاريخ الطلب",
    "ReceivedProducts": "تم استلام المنتجات",
    "ProductReceivedConfirmation": "تم تأكيد استلام المنتجات",
    "YouCanFollowOrderToShipping": "يمكنك متالعه الطلب الان لتوصيلها للعميلة",
    "Services": "الخدمات",
    "DriverInfo": "معلومات السائق",
    "FinishTheService": "انهاء الخدمة",
    "StartTheService": "بدأ الخدمة",
    "Date": "التاريخ",
    "Time": "الوقت",
    "ArrivedToTheLocation": "وصل الى الموقع",
    "Finished": "تم الإنتهاء",
    "GetPaidQR": "الحصول على كود تفعيل مدفوع",
    "SendOTP": "إرسال كود التفعيل",
    "TryAgain": "حاول مرة أخرى",
    "PleaseScanQRCode": "يرجى مسح رمز الاستجابة السريعة",
    "QRCode": "رمز الاستجابة السريعة",
    "YouHaveToRespondWithin15Minutes": "عليك الرد في غضون 15 دقيقة",
    "ReSavedItemQR": "إعادة حفظ رمز الاستجابة السريعة",
    "ReSavedQrReader": "إعادة قارئ رمز الاستجابة السريعة",
    "ReadyToPickUp": "جاهز للاستلام",
    "DeliveredQR": "تسليم رمز الاستجابة السريعة",
    "Resend": "إعادة الإرسال",
    "DeliveredQRReader": "تسليم قارئ رمز الاستجابة السريعة",
    "Waiting": "قيد الإنتظار",
    "CustomerName": "اسم العميل",
    "LaundryName": "اسم المغسلة",
    "LaundryLocation": "عنوان المغسلة",
    "LaundryLocationMap": "عنوان المغسلة على الخريطة",
    "DeliveryLocationMap": "عنوان التوصيل على الخريطة",
    "OnTheWayToPickUp": "في الطريق لالتقاط",
    "PickedUp": "التقط",
    "DeliveredQRCode ": "تسليم رمز الاستجابة السريعة",
    "OnTheWayToTheLaundryShop": "في الطريق إلى المغسلة",
    "Washing": "غسل",
    "YouWillGet50OfDeliveryPriceWhenYouCancelTheOrder": "ستحصل على 50٪ من سعر التوصيل عند إلغاء الطلب",
    "CancelOrder": "إلغاء الطلب",
    "Keep": "البقاء هنا",
    "PickedUpQRCode": "التقط رمز الاستجابة السريعة",
    "Completed": "تم الانتهاء",
    "AreYouSureCancelOrder": "هل تريد إلغاء الطلب",
    "SendOffer": "إرسال عرض"
  },
  "ContactUs": {
    "EnterYourName": "أدخل الاسم",
    "Mobile": "رقم الموبايل",
    "Email": "البريد الإلكتروني",
    "MessageTitle": "عنوان الرسالة",
    "Message": "الرسالة ...",
    "Send": "إرسال",
    "Object": "الموضوع",
    "ContactType": "نوع الاتصال",
    "Name": "الاسم",
    "YouCanSendMessageOrSuggestion": "أو يمكنك إرسال رساله للمساعده أو الاقتراحات و الشكاوى",
    "Subject": "الموضوع",
    "": ""
  },
  "Sitter": {
    "Info": "معلومات الحاضنة",
    "ReservationType": "نوع الحجز",
    "SitterType": "نوع الحاضنة",
    "District": "الحى",
    "ReserveDuration": "مدة الحجز",
    "ReservationInfo": "معلومات الحجز",
    "Date": "التاريخ",
    "Time": "الوقت",
    "NumberOfChildren": "عدد الأطفال",
    "Total": "الاجمالى",
    "ReserveSitter": "حجز الحاضنة",
    "Age": "السن",
    "Nationality": "الجنسية",
    "Certificate": "المؤهل"
  },
  "ProductDetails": {
    "ProductDetails": "تفاصيل المنتج",
    "Evaluations": "التقيمات",
    "ProviderEvaluation": "تقيم العاملة",
    "ServiceAddedSuccessfully": "تم اضافة الخدمة بنجاح",
    "AddToCart": "اضافة الى السلة",
    "ShowMore": "عرض المزيد",
    "Quantity": "الكميه",
    "ProductAddedToCardSuccessfully": "تم اضافه المنتج الى المفضله بنجاح",
    "ServiceAddedToCardSuccessfully": "تم اضافه الخدمه الى المفضله بنجاح",
    "ConfirmPurchasing": "تأكيد الشراء",
    "FollowPurchasing": "متابعه الشراء",
    "AboutService": "عن الخدمه",
    "Features": "المميزات",
    "SpecialAdditions": "اضافات خاصة",
    "DeleteProduct": "حذف المنتج",
    "EditProduct": "تعديل المنتج",
    "SaveEdits": "حفظ التعديلات",
    "AdditionsPrice": "سعر الاضافة",
    "ProductImages": "صور المنتج",
    "productUpdatedSuccessfully": "تم تعديل المنتج بنجاح",
    "Home": "الرئيسية",
    "ChooseDateAndTime": "تحديد الوقت والتاريخ",
    "Date": "التاريخ",
    "Time": "الوقت",
    "AllServices": "مجموع الخدمات",
    "ShippingAddress": "عنوان التوصيل"
  },
  "Auth": {
    "CommercialName": "الإسم التجاري",
    "NickName": "إسم الشهرة",
    "FullName": "الإسم بالكامل",
    "Email": "البريد الإلكتروني",
    "Activation": "تفعيل الحساب",
    "ActivationCode": "كود التفعيل",
    "EnterActivationCode": " أدخل كود التفعيل",
    "UpdatePassword": " تعديل كلمة المرور",
    "FillThisDataForSignUp": "املئ البيانات التاليه لانشاء حسابك",
    "WelcomeInOurApp": "مرحبا بك يمكنك تسجيل الدخول الان",
    "WelcomeBackAgain": "مرحبا بك مرة أخرى",
    "ToFollowYouCanLogin": "للمتابعة يمكنك تسجيل الدخول",
    "LicenseImageOrIndwelling": "صورة الهويه / الاقامة",
    "PracticingTheProfessionPermit": "الشهادة / تصريح المزاولة",
    "LocationOnMap": "العنوان على الخريطة",
    "LocationDesc": "وصف الموقع",
    "TechnicalType": "نوع الفنى",
    "Edit": "تعديل",
    "DelegateName": "اسم المندوب",
    "CreateNewAccount": "إنشاء حساب جديد",
    "AlreadyHaveAccount": " لديك حساب بالفعل : ",
    "Skip": "تخطى",
    "DoesentHaveAccount": "لا يوجد لديك حساب ؟",
    "MobileNumber": "رقم الجوال",
    "Next": "التالي",
    "EditMobileNumber": "تعديل رقم الجوال",
    "Continue": "استمرار",
    "ResendCodeAfter": "اعادة إرسال كود التفعيل",
    "CompleteData": "استكمال البيانات",
    "RestaurantImage": "صورة المطعم",
    "RestaurantLogo": "شعار المطعم",
    "Register": "تسجيل حساب",
    "RegisterConfirmation": "إتمام التسجيل",
    "RegisterAsProvider": "انشاء حساب مقدم خدمه",
    "RegisterAsClient": "انشاء حساب عميل",
    "RestaurantName": "اسم المطعم",
    "EnterRestaurantName": "أدخل اسم المطعم",
    "Category": "القسم",
    "ChooseCategory": "إختر الفئة",
    "Classification": "التصنيف",
    "ChooseClassification": "إختر التصنيف",
    "CommercialRegistrationNo": "رقم السجل التجارى",
    "RegisteredSuccessfully": "تم التسجيل بنجاح",
    "DataWillBeAudited": "سيتم مراجعه البيانات",
    "YouWillBeNotifiedWithAcceptanceOrRefusal": "سيتم اشعارك بالقبول أو الرفض",
    "CodeSentToThisNumber": "تم إرسال الكود لهذا الرقم",
    "UserName": "اسم المستخدم",
    "EnterUserName": "أدخل اسم المستخدم",
    "City": "المدينة",
    "Country": "الدولة",
    "ChooseCity": "اخنر المدينة",
    "Password": "كلمة المرور",
    "CurrentPassword": "كلمة المرور القديمة",
    "NewPassword": "كلمة المرور الجديده",
    "NewPasswordConfirmation": "قم بادخال كلمة المرور الجديده",
    "EnterNewPassword": "الرجاء إنشاء كلمة مرور جديدة",
    "PasswordUpdatedSuccessfully": "تم تغيير كلمة المرور بنجاح",
    "EnterPassword": "أدخل كلمة المرور",
    "EditPassword": "تعديل كلمة المرور",
    "OldPassword": "كلمة المرور القديمة",
    "ConfirmPassword": "تأكيد كلمة المرور",
    "EnterPasswordConfirmation": "أدخل تأكيد كلمة المرور",
    "Login": "تسجيل الدخول",
    "PleaseChooseCountryAndMobile": "فضلا قم باختيار البلد واداخل رقم الجوال",
    "Check": "تحقق",
    "Activate": "تفعيل",
    "LoginCountry": "الدولة : ",
    "LoginMobile": "المدينة : ",
    "ConfirmationCode": "كود التفعيل",
    "EnterConfirmationCodeThatSentTo": "الرجاء إدخال كود التقعيل المرسل إلى جوالك",
    "ResendWithin": "اعاده إرسال في",
    "DoesNotReceivedCode": "لم يصلك كود التفعيل",
    "Resend": "إرسال مرة اخرى",
    "ImageAddedSuccessfully": "تم اضافة الصورة بنجاح",
    "EnterMobileAssociateWithYourMobile": "قم بادخال رقم الجوال المرتبط بحسابك",
    "MobileOrEmail": "رقم الجوال او البريد الإلكتروني",
    "ForgetPassword": "نسيت كلمة المرور"
  },
  "validate": {
    "LocationDesc": "وصف الموقع مطلوب",
    "LicenseImageOrIndwelling": "صورة الهويه / الاقامة مطلوبة",
    "DrivingLicense": "رخصة القيادة مطلوبة",
    "PracticingTheProfessionPermit": "الشهادة / تصريح المزاولة مطلوبة",
    "LocationOnMap": "العنوان على الخريطة مطلوبة",
    "CategoryOrTransferType": "الفئة /  نوع النقل مطلوبة",
    "CarForm": "استمارة السيارة مطلوبة",
    "CarImage": "صورة السيارة مطلوبة",
    "name": "الاسم مطلوب",
    "phone": "رقم الجوال مطلوب",
    "TechnicalType": "نوع الفنى",
    "email": "البريد الإلكتروني مطلوب",
    "country": "الدولة مطلوبة",
    "city": "المدينة مطلوبة",
    "VisitTime": "وقت الزياره مطلوب",
    "location": "العنوان على الخريطة مطلوب",
    "password": "كلمة المرور مطلوبة",
    "CorrectPassword": "أدخل كلمة مرور اكير من 6 عناصر",
    "ValidPassword": "تأكد من ادخال كلمتي مرور متشابهتان",
    "code": "كود التفعيل مطلوب",
    "ProfilePic": "الصورة الشخصية مطلوبة",
    "ValidEmail": "ادخل بريد الكتروني صحيح",
    "ValidMobile": "يجب ان يحتوي علي 8 ارقام على الأقل",
    "ValidCode": "أدخل كود تفعيل صحيح",
    "Address": "العنوان مطلوب",
    "ReceivedLocation": "عنوان الاستلام مطلوب",
    "TransferLocation": "عنوان التسليم مطلوب",
    "Category": "الفئة مطلوبة",
    "Description": "الوصف مطلوب",
    "ShippingType": "نوع النقل مطلوب",
    "price": "السعر مطلوب",
    "Image": "الصورة مطلوبة",
    "Images": "الصور مطلوبة",
    "message": "الرسالة مطلوبة",
    "title": "العنوان مطلوب",
    "time": "الوقت مطلوب",
    "CardOwnerName": "اسم صاحب البطاقة مطلوب",
    "CardNumber": "رقم البطاقه مطلوب",
    "ExpiredDate": "تاريخ الانتهاء مطلوب",
    "Cvv": "الرقم السري Cvv مطلوب",
    "Instructions": "تعليمات للموصل مطلوبة",
    "AddressType": "نوع العنوان مطلوب",
    "FlatNumber": "رقم الشقه مطلوب",
    "NearestPlace": "اقرب معلم مطلوب",
    "Benefits": "المميزات مطلوبه",
    "address": "العنوان مطلوب",
    "PaymentWay": "طريقةالدفع مطلوبة",
    "Rate": "التقيم مطلوب",
    "Comment": "التعليق مطلوب",
    "ProblemLocation": "عنوان المشكله مطلوب",
    "ProblemImages": "صور المشكله مطلوبة",
    "ProblemDesc": "وصف المشكله مطلوب",
    "SuitableCategory": "الفنى المناسب مطلوب",
    "ChildInfo": "معلومات الطفل مطلوبة",
    "Living": "السكن مطلوب",
    "Attachments": "المرفقات مطلوبة",
    "ChildName": "اسم الطفل مطلوب",
    "InPocoParentis": "ولى الأمر مطلوب",
    "inPocoParentisName": "اسم ولى الأمر مطلوب",
    "Gender": "الحنس مطلوب",
    "Male": "ذكر",
    "FeMale": "أنثى",
    "DateOfBirth": "تاريخ الميلاد مطلوب",
    "BirthPlace": "مكان الميلاد مطلوب",
    "NumberOfBrothersAndSisters": "عدد الأخوه والأخوات مطلوب",
    "ChildRankBetweenBrotherHood": "ترتيب الطفل بين أخوته مطلوب",
    "BabyNameQuadruple": "اسم الطفل رباعى مطلوب",
    "InPocoParentisMobile": "رقم جوال ولى الأمر مطلوب",
    "Kinship": "صلة القرابة مطلوب",
    "Subject": "الموضوع مطلوب",
    "EducationQualification": "المؤهل التعليمي مطلوب",
    "JobTitle": "المسمى الوظيفى مطلوب",
    "Workplace": "مكان العمل مطلوب",
    "WorkPhone": "هاتف العمل مطلوب",
    "ClientResidence": "محل اقامه الطفل مطلوب",
    "MainRoadNameAndBuildingNumber": "اسم الشارع الرئيسي-رقم المبنى مطلوب",
    "NationalAddress": "العنوان الوطني مطلوب",
    "Next": "التالي",
    "Nationality": "الحنسية مطلوبة",
    "FamilyCardPhoto": "صورة بطاقه العائلة مطلوبة",
    "BirthCertificatePicture": "صورة شهاده الميلاد مطلوبة",
    "ChildProfilePicture": "صورة شخصية للطفل مطلوبة",
    "HealthCertificatePictures": "صورة الشهادة الصحية مطلوبة",
    "VaccinationCertificatePictures": "صورة شهاة التطعيم مطلوبة",
    "UploadMedicalCertificate": "الشهاده الصحيه مطلوبة",
    "UploadMedicalInsuranceCertificate": "شهاده التأمين الطبى مطلوبة",
    "UploadVaccinationCertificate": "شهاده التطعيم مطلوبة",
    "Object": "الموضوع مطلوب",
    "ContactType": "نوع الاتصال مطلوب",
    "CardHolder": "اسم حامل البطاقه مطلوب",
    "CVV": "رقم الكود مطلوب",
    "SerialNo": "رقم المسلسل مطلوب",
    "AccountName": "اسم الحساب مطلوب",
    "BankName": "اسم البنك مطلوب",
    "AccountNumber": "رقم الحساب مطلوب",
    "Iban": "رقم الايبان مطلوب",
    "Title": "العنوان مطلوب",
    "StartDate": "تاريخ البداية مطلوب",
    "EndDate": "تاريح النهاية مطلوب",
    "Code": "الكود مطلوب",
    "OfferUsed": "العرض المستخدم مطلوب",
    "MaximumNumberUfUse": "الحد الأقصى لعدد الإستخدام مطلوب",
    "CommercialName": "الإسم التجاري مطلوب",
    "NickName": "إسم الشهرة مطلوب",
    "FullName": "الإسم بالكامل مطلوب",
    "TargetAdvertiserCategory": "فئة الإعلان المستهدف مطلوبة",
    "ItemOrProductDescription": "وصف السلعة/المنتج/الخدمة مطلوب",
    "RequiredAdDate": "تاريخ الإعلان مطلوب",
    "AdResidence": "مقر الإعلان مطلوب",
    "AdDuration": "مدة الإعلان بالدقيقة مطلوب",
    "AdVia": "الإعلان عبر مطلوب",
    "PleaseAcceptTerms": "قم بقبول الشروط والأحكام الخاصة بالتطبيق"
  },
  "Successfully": {
    "ServiceCreated": "تم إرسال الخدمة بنجاح",
    "OrderCreated": "تم إرسال الطلب بنجاح",
    "OrderRejected": "تم رفض الطلب بنجاح",
    "OrderCancelled": "تم إلغاء الطلب بنجاح",
    "AccountCreated": "تم إنشاء الحساب بنجاح",
    "profileUpdate": "تم تعديل بيانات الحساب",
    "RateCreated": "تم التقيم بنجاح",
    "Send": "تم الإرسال بنجاح",
    "PasswordSaved": "تم حفظ كلمة المرور بنجاح",
    "OrderSent": "تم إرسال طلبك بنجاح",
    "MessageSent": "تم إرسال الرسالة بنجاح",
    "PriceOfferSent": "تم إرسال عرض السعر بنجاح",
    "PriceOfferRejected": "تم رفض عرض السعر",
    "OrderAcceptedAndConfirmed": "تم قبول وتأكيد الطلب بنجاح",
    "NotificationDeleted": "تم حذف الإشعار بنجاح",
    "InfoUpdated": "تم تعديل البيانات بنجاح",
    "ServiceConfirmed": "تم تنفيذ الخدمة بنجاح"
  },
  "Cart": {
    "Cart": "السلة",
    "FollowPurchasing": "متابعة الشراء",
    "Total": "الاجمالى",
    "PaymentWay": "طريقة الدفع",
    "Cash": "الدفع نقدا",
    "PaymentViaCard": "الدفع عن طريق البطاقة",
    "PaymentViaCreditCard": "الدفع عن طريق البطاقة الائتمانية",
    "OrderSummary": "ملخص الطلب",
    "FinishOrder": "انهاءالطلب",
    "ChangeAddress": "تغيير العنوان",
    "CardOwnerName": "اسم صاحب البطاقة ",
    "CardNumber": "رقم البطاقه",
    "ExpiredDate": "تاريخ الانتهاء",
    "Cvv": "الرقم السري Cvv",
    "ConfirmInfo": "تأكيد البيانات",
    "ThanksForUsingBeatrice": "شكرا لاختيارك بياتريس",
    "YouCanFollowOrderNow": "يمكنك متابعه طلبك الان",
    "Home": "الرئيسية",
    "FollowOrder": "متابعة الطلب"
  },
  "Auctions": {
    "AuctionStartWith": "يبدأ المزاد ب",
    "RemainingTime": "الوقت المتبقى",
    "currency": "sar",
    "Share": "مشاركة",
    "Code": "الكود",
    "Viewers": "مشاهدات",
    "Likes": "اعجابات",
    "AvailableAuction": "المزاد جارى",
    "HigherValueOfAuction": "أعلى قيمة مزايدة",
    "MinimumValue": "الحد الأدنى للمزايدة",
    "AuctionAddress": "عنوان المزاد",
    "AuctionDescription": "وصف المزاد",
    "AuctionDuration": "مدة المزاد",
    "Day": "يوم",
    "Hour": "ساعه",
    "Minute": "دقيقه",
    "Second": "ثانيه",
    "Add": "اضافة",
    "YouCanAddImages": "بمكنك اضافة صور",
    "YouCanAddVideo": "بمكنك اضافة مقطع فيديو",
    "SubscribeInAuctionPackages": "اشترك بباقات المزاد",
    "EnjoyBiddingAndBuying": "واستمتع بالشراء والمزايده",
    "Packages": "الباقات",
    "Pay": "دفع",
    "ForParticipationInAuctionYouMustSubscribeInOnePackage": "للمشاركة في المزاد بتوجب الاشتراك في احدى الباقات"
  },
  "Addresses": {
    "Addresses": "العناوين",
    "AddAddress": "اضافة عنوان",
    "AnyInstructionsToDriver": "اي تعليمات للموصل ؟",
    "AddressType": "نوع العنوان",
    "FlatNo": "رقم الشقه",
    "NearestGuide": "اقرب معلم",
    "SetAsDefault": "تعين كافتراضي",
    "Delete": "مسح",
    "Edit": "تعديل العنوان",
    "ChooseAddress": "إختر العنوان"
  },
  "CompleteOrder": {
    "RequiredMoney": "المبلغ المستحق",
    "WorkingOnSolveProblem": "العمل على حل مشكلة العميل",
    "ClientWillPay": "سوف يقوم العميل بدفع المبلغ المستحق عند الانتهاء من حل المشكله",
    "Total": "المبلغ الاجمالى",
    "ServiceCompleted": "اكتمل الصيانه",
    "SendRate": "ارسل تقييم",
    "SkipRate": "تحطى التقييم",
    "Rate": "تقييم",
    "RateClient": "تقييم العميل"
  },
  "BankAccount": {
    "BankAccountInfo": "بينانات حسابك البنكى",
    "UserName": "اسم صاحب الحساب",
    "BankName": "اسم البنك",
    "IbanNumber": "رقم الأى بان",
    "AccountNumber": "رقم الحساب",
    "CashOut": "صرف نقدى"
  },
  "Setting": {
    "PrivacyAndPolicy": "سياسة الخصوصية",
    "QA": "الأسئله الشائعه",
    "Language": "اللغه ( English )",
    "SwitchToBusiness": "الترقية الي حساب تجارى",
    "NewMessage": "رسالة جديدة",
    "NewOrder": "طلب جديد",
    "NewReview": "تقيم جديد",
    "Freelancer": "عامل حر",
    "Shop": "شركة",
    "ChooseTheTypeOfYourAccount": "قم باختيار نوع الحساب",
    "Next": "التالي",
    "BusinessAccount": "حساب تجارى",
    "WhatAreFieldsThatYouInterestingIn": "",
    "Designing": "تصميم",
    "Writing": "كتابة",
    "Programming": "برمجه",
    "ShopInformation": "بيانات الشركة",
    "ShopName": "اسم الشركة",
    "BusinessRegister": "تسجيل شركة",
    "Location": "العنوان"
  },
  "RequestProvider": {
    "Follow": "متابعة",
    "RequestProvider": "طلب فنى",
    "ProblemLocation": "عنوان المشكلة",
    "ProblemImages": "صور المشكلة",
    "ProblemDesc": "وصف المشكله",
    "SuitableCategory": "إختر الفنى المناسب"
  }
};
static const Map<String,dynamic> en_US = {
  "Main": {
    "Title": "Beatrice",
    "English": "English",
    "Arabic": "Arabic",
    "Accept": "Accept",
    "Delete": "Delete",
    "Reject": "Reject",
    "currency": "sar",
    "LanguageTransformation": "العربية",
    "TryAgain": "Try again",
    "reset_locale": "Reset Saved Language",
    "Gallery": "Gallery",
    "Send": "Send",
    "Cancel": "Cancel",
    "Camera": "Camera",
    "Search": "Search",
    "CheckInternetConnection": "Check internet connection",
    "Loading": "Loading ...",
    "noConnection": "No Internet Connection",
    "boorConnection": "Poor Internet",
    "serverError": "Server Error try again later"
  },
  "Search": {
    "WriteYourSearchKeyWordHere": "Write your search key word here",
    "SearchHere": "Search here",
    "Search": "Search",
    "ChooseCategory": "Choose category",
    "ChooseSubcategory": "Choose subcategory",
    "NoSearchDataFound": "No search data found"
  },
  "Orders": {
    "OrderAddress": "Order address",
    "ConfirmOrder": "Confirm order",
    "Description": "Description",
    "ReceiptLocation": "Receipt location",
    "DeliveryLocation": "Delivery location",
    "OrderLocation": "Order location",
    "Current": "Current",
    "InProgress": "In progress",
    "Finished": "Finished",
    "Products": "Products",
    "CurrentOrders": "Current orders",
    "ConfirmedOrders": "Confirmed orders",
    "AcceptAndSendPriceOffer": "Accept and send price offer",
    "EnterRequiredPriceToConfirmService": "Enter required price to provide the service",
    "Services": "Services",
    "ShippingAddress": "Shipping address",
    "OrderStatus": "Order status",
    "OrderInfo": "Order info",
    "AddOrder": "Add order",
    "ChooseTargetAdvertiserCategory": "Choose advertiser category",
    "TargetAdvertiserCategory": "Target advertiser category",
    "CreateNewRequestForm": "Create a new request form",
    "ItemOrProductDescription": "Product / service / commodity description",
    "RequiredAdDate": "Required ad date",
    "AdResidence": "Ad venue",
    "AdDuration": "Ad duration by minute",
    "AdVia": "Ad via",
    "OpenedOrder": "Opened order",
    "ConfirmedOrder": "Confirmed order",
    "ShowOrder": "Show order",
    "CancelOrder": "Cancel order",
    "MyCurrentOrder": "My current orders",
    "MyConfirmedOrder": "My completed orders",
    "OrderProviderInfo": "Order provider info",
    "RejectOrder": "Reject order"
  },
  "Offers": {
    "OfferDetails": "Offer Details",
    "Offers": "Offers",
    "Title": "Title",
    "StartDate": "Start date",
    "EndDate": "End date",
    "Code": "Code",
    "OfferUsed": "Offer used",
    "MaximumNumberUfUse": "Maximum number of use",
    "AddOffer": "Add Offer",
    "EditOffer": "Edit Offer",
    "UploadOfferPhoto": "Upload offer photo",
    "MaximumNumberOfUse": "Maximum number of use",
    "OfferFees": "Offer fees",
    "Add": "Add",
    "Clear": "Clear",
    "InActive": "Inactive",
    "Discount": "Discount",
    "Edit": "Edit",
    "AreYouSureAboutReactiveThisOffer": "Are you sure about reactive this offer?",
    "YouHaveToWaitAdminApproval": "You have to wait admin approval",
    "PaymentSuccessfully": "Payment successfully ",
    "FeesAreNonRefundable": "Fees are non-refundable",
    "AreYouSureAboutDeactivateThisOffer": "Are you sure about deactivate this offer?",
    "DeActivate": "De-Activate",
    "Cancel": "Cancel"
  },
  "Home": {
    "OrdersFromManagement": "Orders from management",
    "NewOrder": "New order",
    "OrderNumber": "Order number",
    "ClientName": "Client name",
    "OrderTime": "Visit time",
    "More": "More",
    "ServicesCategories": "Services categories",
    "ProductsCategories": "Products categories",
    "BestProducts": "Best products"
  },
  "AddProduct": {
    "ProductImages": "Product images",
    "ProductAddedSuccessfully": "Product added successfully",
    "ProductEditedSuccessfully": "Product edited successfully",
    "SaveEdits": "Save edits",
    "ProductName": "Product name",
    "Category": "Category",
    "SubCategory": "Subcategory",
    "ShortDescription": "Short description",
    "SpecialAdditions": "Special additions",
    "AdditionPrice": "Addition Price",
    "AddProduct": "Add product",
    "Add": "Add",
    "EditProduct": "Edit product"
  },
  "Drawer": {
    "AppWelcomesYou": "App welcomes you",
    "PersonalData": "Personal data",
    "AddAd": "Add ad",
    "MyAds": "My ads",
    "Binders": "Binders",
    "AppAgency": "App agencyِ",
    "RentContract": "Rent contract",
    "PushQuest": "Push quest",
    "CustomerService": "Customer service",
    "ShareApp": "Share app"
  },
  "Idea": {
    "AddIdea": "Add idea",
    "EditIdea": "Edit idea",
    "IdeaAddress": "Idea address",
    "IdeaDesc": "Idea desc",
    "IdeaDuration": "Idea duration",
    "Add": "Idea duration",
    "Edit": "Edit",
    "YouMustPutExplanationToAvoidTheft": "You must put explanation to avoid theft",
    "ValidateIdeaAddress": "Idea address is required",
    "ValidateIdeaImages": "Idea images is required",
    "ValidateIdeaDuration": "Idea duration is required",
    "MyIdeas": "My ideas"
  },
  "BottomNavigation": {
    "Language": "Language",
    "Conversations": "Conversations",
    "Notifications": "Notifications",
    "Home": "Home",
    "MyOrders": "My orders",
    "Profile": "Profile",
    "Messages": "messages",
    "More": "More",
    "DoYouWantCloseApp": "Do you want to close the app",
    "Yes": "Yes",
    "No": "No"
  },
  "More": {
    "PersonalData": "Personal data",
    "ChangeLanguage": "Change language",
    "Wallet": "Wallet",
    "PaymentWays": "Payment ways",
    "UsingPolicy": "Using policy",
    "TermsAndConditions": "Terms and conditions",
    "ShareApp": "ShareApp",
    "ContactUs": "Contact us",
    "AboutApp": "About Us",
    "Terms": "Terms & conditions",
    "Policy": "Policy",
    "AddYourAd": "Add your ad",
    "MyAds": "My ads",
    "AddAuction": "Add auction",
    "MyAuctions": "My auctions",
    "Favourite": "Favourite",
    "BonusPoints": "Bonus points",
    "LogOut": "Log Out",
    "Evaluations": "Evaluations",
    "HealthCertificate": "Health certificate",
    "DeliveryAndReceiveChild": "Delivery and receive child",
    "MandateDeliveryAndReceive": "Mandate delivery and receive",
    "CallUs": "Call us",
    "QrCode": "QrCode",
    "Settings": "Settings",
    "Reviews": "Reviews",
    "Save": "Save"
  },
  "Sitter": {
    "Info": "Sitter info",
    "ReservationType": "Reservation type",
    "SitterType": "SitterType",
    "District": "District",
    "ReserveDuration": "Reserve duration",
    "ReservationInfo": "Reservation info",
    "Date": "Date",
    "Time": "Time",
    "NumberOfChildren": "Number of children",
    "Total": "Total",
    "ReserveSitter": "Reserve sitter",
    "Age": "Age",
    "Nationality": "Nationality",
    "Certificate": "Certificate"
  },
  "ReserveConfirmation": {
    "ReserveConfirmation": "Reserve confirmation",
    "ChildInfo": "Child info",
    "Living": "Living",
    "Attachments": "Attachments",
    "ChildName": "Child name",
    "BabyNameQuadruple": "Baby's name quadruple",
    "InPocoParentis": "In poco parentis",
    "inPocoParentisName": "in poco parentis name",
    "Gender": "Gender",
    "Male": "Male",
    "FeMale": "Female",
    "DateOfBirth": "Date of birth",
    "BirthPlace": "Birth place",
    "NumberOfBrothersAndSisters": "Number of brothers and sisters",
    "ChildRankBetweenBrotherHood": "Child rank between brotherhood",
    "InPocoParentisMobile": "in poco parentis mobile",
    "Kinship": "Kinship",
    "EducationQualification": "Education qualification",
    "JobTitle": "Job title",
    "Workplace": "Workplace",
    "WorkPhone": "Work phone",
    "ClientResidence": "Client residence",
    "MainRoadNameAndBuildingNumber": "Main road name and building number",
    "NationalAddress": "National address",
    "Next": "Next",
    "FamilyCardPhoto": "Family card photo",
    "BirthCertificatePicture": "Birth certificate picture",
    "ChildProfilePicture": "Child profile picture",
    "HealthCertificatePictures": "Health certificate pictures",
    "VaccinationCertificatePictures": "Vaccination certificate pictures",
    "AddAnotherChild": "Add another child",
    "ThanksYourReservationDoneSuccessfullyNow": "Thanks your reservation done successfully now",
    "PleaseWaitForSitterAcceptance": "Please wait for sitter acceptance",
    "UploadMedicalCertificate": "Upload medical certificate",
    "UploadMedicalInsuranceCertificate": "Upload medical insurance certificate",
    "NotRequiredIfAvailable": "Not required if available",
    "UploadVaccinationCertificate": "Upload vaccination certificate",
    "RenewVia6Months": "RenewVia 6 months",
    "HealthCertificate": "Health certificate"
  },
  "OrderDetails": {
    "ServiceConfirmed": "Service confirmed",
    "OrderNumber": "Order number",
    "OrderDetails": "Order details",
    "AcceptOrder": "Accept order",
    "RejectOrder": "Reject order",
    "FinishOrder": "Finish order",
    "Products": "Products",
    "NotesFromClient": "Notes from client",
    "AddressDetails": "Address details",
    "OrderSummary": "Order summary",
    "AdditionalTax": "Additional tax",
    "ServicePrice": "Service price",
    "Total": "Total",
    "Note": "Note",
    "Prepared": "Prepared",
    "ContactWithCustomer": "Contact with customer",
    "Delivered": "Delivered",
    "ThanksForDelivery": "Thanks for delivery",
    "YouCanFollowNewOrders": "You can follow new orders",
    "Orders": "Orders",
    "YouCanFollowOrderToConfirmDelegateArrival": "You can follow order to confirm delegate arrival",
    "FollowOrder": "Follow order",
    "ServerInfo": "Server info",
    "ClientInfo": "Client info",
    "ClientLocation": "Client location",
    "TotalProducts": "Total products",
    "ShippingPrice": "Shipping price",
    "TaxAmount": "Tax amount",
    "ShippedProducts": "Products is shipped",
    "ShowAll": "Show all",
    "ConfirmedShippingProducts": "Shipping products confirmed successfully",
    "YouCanReceiveNewOrders": "You can receive new orders",
    "Home": "Home",
    "OrderDate": "Order date",
    "ReceivedProducts": "Products received",
    "ProductReceivedConfirmation": "Products received confirmation",
    "YouCanFollowOrderToShipping": "You can follow order to shipping products",
    "Services": "Services",
    "DriverInfo": "Driver info",
    "FinishTheService": "Finish the service",
    "StartTheService": "Start the service",
    "Date": "Date",
    "Time": "Time",
    "ArrivedToTheLocation": "Arrived to the location",
    "Finished": "Finished",
    "GetPaidQR": "Get paid QR",
    "SendOTP": "Send  OTP",
    "TryAgain": "Try again",
    "PleaseScanQRCode": "Please Scan QR Code",
    "QRCode": "QR code",
    "YouHaveToRespondWithin15Minutes": "You have to respond within 15 minutes ",
    "ReSavedItemQR": "ReSaved item QR",
    "ReSavedQrReader": "ReSaved QR reader",
    "ReadyToPickUp": "Ready to pick up",
    "DeliveredQR": "Delivered QR",
    "Resend": "Resend",
    "DeliveredQRReader": "Delivered QR reader",
    "Waiting": "Waiting",
    "CustomerName": "Customer name",
    "LaundryName": "Laundry name",
    "LaundryLocation": "Laundry location",
    "LaundryLocationMap": "Laundry location map",
    "DeliveryLocationMap": "Delivery location map",
    "OnTheWayToPickUp": "On the way to pick up",
    "PickedUp": "Picked up",
    "DeliveredQRCode ": "Delivered QR code ",
    "OnTheWayToTheLaundryShop": "On the way to the laundry shop",
    "Washing": "Washing",
    "YouWillGet50OfDeliveryPriceWhenYouCancelTheOrder": "You will get 50% of delivery price when you cancel the order",
    "CancelOrder": "Cancel order",
    "Keep": "Keep",
    "PickedUpQRCode": "Picked up QR code",
    "Completed": "Completed",
    "AreYouSureCancelOrder": "Are you sure cancel order",
    "SendOffer": "Send Offer"
  },
  "ProductDetails": {
    "ProductDetails": "Product details",
    "ProviderEvaluation": "Provider evaluation",
    "Evaluations": "Evaluations",
    "ServiceAddedSuccessfully": "Service added successfully",
    "AddToCart": "Add to cart",
    "ShowMore": "Show more",
    "Quantity": "Quantity",
    "ProductAddedToCardSuccessfully": "Product added to card successfully",
    "ServiceAddedToCardSuccessfully": "Service added to card successfully",
    "ConfirmPurchasing": "Confirm purchasing",
    "FollowPurchasing": "Follow purchasing",
    "AboutService": "About service",
    "Features": "Features",
    "SpecialAdditions": "Special additions",
    "DeleteProduct": "Delete product",
    "EditProduct": "Edit product",
    "SaveEdits": "Save edits",
    "AdditionsPrice": "Additions price",
    "ProductImages": "Product images",
    "productUpdatedSuccessfully": "product updated successfully",
    "Home": "Home",
    "ChooseDateAndTime": "Choose date and time",
    "Date": "Date",
    "Time": "Time",
    "AllServices": "All services",
    "ShippingAddress": "Shipping address"
  },
  "ContactUs": {
    "EnterYourName": "Enter your name",
    "ContactUs": "Contact us",
    "Mobile": "Mobile",
    "Email": "Email",
    "MessageTitle": "Message title",
    "Message": "Message ...",
    "Send": "Send",
    "Object": "Object",
    "Subject": "Subject",
    "ContactType": "Contact type",
    "Name": "Name",
    "YouCanSendMessageOrSuggestion": "You can send message or suggestion"
  },
  "Auth": {
    "CommercialName": "Commercial name ",
    "ActivationCode": "Activation code ",
    "EnterActivationCode": "Enter activation code ",
    "NickName": "Nick name",
    "FullName": "Full name",
    "VetName": "Vet name",
    "Activation": "Account activation",
    "FillThisDataForSignUp": "Fill this data for sign up",
    "WelcomeInOurApp": "Welcome you can sign in now",
    "WelcomeBackAgain": "Welcome back again",
    "ToFollowYouCanLogin": "Tp follow you can login",
    "BarberName": "Barber name",
    "Email": "Email",
    "UpdatePassword": "Update password",
    "LicenseImageOrIndwelling": "License image or indwelling",
    "PracticingTheProfessionPermit": "Practicing the profession permit",
    "LocationOnMap": "Location on map",
    "LocationDesc": "Location description",
    "Edit": "Update",
    "TechnicalType": "Technical type",
    "DoesentHaveAccount": "Doesen't have account ?",
    "DelegateName": "Delegate name",
    "CategoryOrTransferType": "Category or transfer type",
    "CarForm": "Car form",
    "CarImage": "Car image",
    "CreateNewAccount": "Create new account",
    "RegisterAsBarber": "Register as barber",
    "RegisterAsProvider": "Register as provider",
    "RegisterAsClient": "Register as Client",
    "RegisterAsVet": "Register as vet",
    "RegisterAsDriver": "Register as driver",
    "AlreadyHaveAccount": "Already have account : ",
    "AlreadyHaveClientAccount": "Already have client account ",
    "AlreadyHaveProviderAccount": "Already have provider account",
    "Skip": "Skip",
    "UseAppAs": "Use app as",
    "Provider": "Provider",
    "Driver": "Driver",
    "MobileNumber": "Phone No.",
    "Next": "Next",
    "EditMobileNumber": "Edit mobile number",
    "Continue": "Continue",
    "ResendCodeAfter": "Resend code after",
    "CompleteData": "Complete data",
    "RestaurantImage": "Restaurant image",
    "RestaurantLogo": "Restaurant logo",
    "Activate": "Activate",
    "Day": "Day",
    "Hour": "Hour",
    "Minute": "Minute",
    "Second": "Second",
    "Register": "Register",
    "RegisterConfirmation": "Register confirmation",
    "RestaurantName": "Restaurant name",
    "EnterRestaurantName": "Enter restaurant name",
    "Category": "Category",
    "ChooseCategory": "Choose category",
    "Classification": "Classification",
    "ChooseClassification": "Choose classification",
    "CommercialRegistrationNo": "Commercial registration no",
    "RegisteredSuccessfully": "Registered successfully",
    "DataWillBeAudited": "Data will be audited",
    "YouWillBeNotifiedWithAcceptanceOrRefusal": "You will be notified with acceptance or refusal",
    "CodeSentToThisNumber": "Code Sent to this number",
    "UserName": "User name",
    "DrivingLicense": "Driving license",
    "EnterUserName": "Enter user name",
    "City": "City",
    "Country": "Country",
    "ChooseCity": "Choose city",
    "Password": "Password",
    "EnterPassword": "Enter password",
    "NewPassword": "New password",
    "EnterNewPassword": "Enter new password",
    "NewPasswordConfirmation": "Confirm new password",
    "PasswordUpdatedSuccessfully": "Password updated successfully",
    "EditPassword": "Change password",
    "OldPassword": "Old password",
    "ConfirmPassword": "Confirm password",
    "EnterPasswordConfirmation": "Enter password confirmation",
    "Login": "Log in",
    "PleaseChooseCountryAndMobile": "Please choose country and mobile",
    "Check": "Check",
    "LoginCountry": "Country : ",
    "LoginMobile": "Mobile : ",
    "ConfirmationCode": "Confirmation code",
    "EnterConfirmationCodeThatSentTo": "Enter confirmation code that sent to",
    "ResendWithin": "Resend within",
    "DoesNotReceivedCode": "Doesn't  received code",
    "EnterMobileAssociateWithYourMobile": "Enter mobile associate with your mobile",
    "Resend": "Resend",
    "MobileOrEmail": "Mobile or email",
    "ImageAddedSuccessfully": "Image added successfully",
    "ForgetPassword": "Forgot password?"
  },
  "validate": {
    "LocationDesc": "Location description is required",
    "name": "User name is required",
    "email": "Email is required",
    "TechnicalType": "Technical type is required",
    "country": "Country is required",
    "city": "City is required",
    "location": "Location is required",
    "VisitTime": "Visit time is required",
    "password": "Password is required",
    "CorrectPassword": "Please enter password more than 6 digits",
    "ValidPassword": "Passwords must be same",
    "code": "Activation code is required",
    "LicenseImageOrIndwelling": "License image or indwelling is required",
    "PracticingTheProfessionPermit": "Practicing the profession permit is required",
    "LocationOnMap": "Location on map is required",
    "CategoryOrTransferType": "Category or transfer type is required",
    "CarForm": "Car form is required",
    "CarImage": "Car image is required",
    "ProfilePic": "Profile picture is required",
    "DrivingLicense": "Driving license is required",
    "ValidEmail": "Enter a valid email",
    "ValidCode": "Enter a valid code",
    "phone": "Mobile number is required",
    "ValidMobile": "Mobile must contain at least 8 numbers",
    "Address": "Address is required",
    "ReceivedLocation": "Received location is required",
    "TransferLocation": "Transfer location is required",
    "Category": "Category is required",
    "Description": "Description is required",
    "ShippingType": "ShippingType is required",
    "price": "price is required",
    "Image": "Image is required",
    "Images": "Images is required",
    "message": "message is required",
    "title": "title is required",
    "time": "time is required",
    "CardOwnerName": "Card owner name is required",
    "CardNumber": "Card number is required",
    "ExpiredDate": "Expired date is required",
    "Cvv": "Cvv is required",
    "Instructions": "Instructions is required",
    "AddressType": "Address type is required",
    "FlatNumber": "Flat number is required",
    "NearestPlace": "Nearest place is required",
    "Benefits": "Benefits is required",
    "address": "address required",
    "PaymentWay": "Payment way is required",
    "Rate": "Rate is required",
    "Comment": "Comment is required",
    "ProblemLocation": "Problem location is required",
    "ProblemImages": "Problem images is required",
    "ProblemDesc": "Problem description is required",
    "SuitableCategory": "Suitable category is required",
    "ChildInfo": "Child info is required",
    "Living": "Living is required",
    "Attachments": "Attachments is required",
    "ChildName": "Child name is required",
    "InPocoParentis": "In poco parentis is required",
    "inPocoParentisName": "in poco parentis name is required",
    "Gender": "Gender is required",
    "DateOfBirth": "Date of birth  is required",
    "BirthPlace": "Birth place is required",
    "NumberOfBrothersAndSisters": "Number of brothers and sisters is required",
    "ChildRankBetweenBrotherHood": "Child rank between brotherhood is required",
    "InPocoParentisMobile": "in poco parentis mobile",
    "Kinship": "Kinship is required",
    "EducationQualification": "Education qualification is required",
    "JobTitle": "Job title is required",
    "Workplace": "Workplace is required",
    "WorkPhone": "Work phone is required",
    "ClientResidence": "Client residence is required",
    "MainRoadNameAndBuildingNumber": "Main road name and building number is required",
    "NationalAddress": "National address is required",
    "FamilyCardPhoto": "Family card photo is required",
    "BirthCertificatePicture": "Birth certificate picture is required",
    "ChildProfilePicture": "Child profile picture is required",
    "HealthCertificatePictures": "Health certificate pictures is required",
    "BabyNameQuadruple": "Baby's name quadruple is required",
    "VaccinationCertificatePictures": "Vaccination certificate pictures is required",
    "UploadMedicalCertificate": "MedicalC certificate is required",
    "UploadMedicalInsuranceCertificate": "Medical insuranceCertificate is required",
    "HealthCertificate": "Health certificate is required",
    "Object": "Object is required",
    "Subject": "Subject is required",
    "ContactType": "Contact type is required",
    "CardHolder": "Card holder is required",
    "CVV": "CVV is required",
    "SerialNo": "Serial no is required",
    "AccountName": "Account name is required",
    "BankName": "Bank name is required",
    "AccountNumber": "Account number is required",
    "Iban": "IBAN is required",
    "Title": "Title is required",
    "StartDate": "Start date is required",
    "EndDate": "End date is required",
    "Nationality": "Nationality is required",
    "Code": "Code is required",
    "OfferUsed": "Offer used is required",
    "MaximumNumberUfUse": "Maximum number of use is required",
    "CommercialName": "Commercial name  is required",
    "NickName": "Nick name is required",
    "FullName": "Full name is required",
    "TargetAdvertiserCategory": "Target advertiser category is required",
    "ItemOrProductDescription": "description is required",
    "RequiredAdDate": "Required ad date is required",
    "AdResidence": "Ad venue is required",
    "AdDuration": "Ad duration by minute is required",
    "AdVia": "Ad via is required",
    "PleaseAcceptTerms": "Please accept app terms and conditions"
  },
  "Successfully": {
    "OrderCreated": "Order created successfully",
    "OrderRejected": "Order rejected successfully",
    "OrderCancelled": "Order cancelled successfully",
    "profileUpdate": "Profile updated successfully",
    "AccountCreated": "Account created successfully",
    "RateCreated": "Rate created successfully",
    "Send": "Sent successfully successfully",
    "PasswordSaved": "Password saved successfully",
    "OrderSent": "Order sent successfully",
    "MessageSent": "Message sent successfully",
    "PriceOfferSent": "Price offer sent successfully",
    "PriceOfferRejected": "Price offer rejected successfully",
    "OrderAcceptedAndConfirmed": "Order accepted and confirmed successfully",
    "NotificationDeleted": "Notification deleted successfully",
    "InfoUpdated": "Info updated successfully",
    "ServiceConfirmed": "Service confirmed successfully"
  },
  "Cart": {
    "Cart": "Cart",
    "FollowPurchasing": "Follow purchasing",
    "Total": "Total",
    "PaymentWay": "Payment way",
    "Cash": "Cash",
    "PaymentViaCard": "Payment via card",
    "PaymentViaCreditCard": "Payment via credit card",
    "OrderSummary": "Order summary",
    "FinishOrder": "Finish order",
    "ChangeAddress": "Change address",
    "CardOwnerName": "Card owner name",
    "CardNumber": "Card number",
    "ExpiredDate": "Expired date",
    "Cvv": "Cvv",
    "ConfirmInfo": "Confirm info",
    "ThanksForUsingBeatrice": "Thanks for using beatrice",
    "YouCanFollowOrderNow": "You can follow order now",
    "Home": "Home",
    "FollowOrder": "Follow order"
  },
  "Auctions": {
    "AuctionStartWith": "Auction start with",
    "RemainingTime": "Remaining time",
    "currency": "sar",
    "Share": "Share",
    "Code": "Code",
    "Viewers": "Viewers",
    "Likes": "Likes",
    "AvailableAuction": "Available auction",
    "HigherValueOfAuction": "Higher value of auction",
    "MinimumValue": "Minimum value",
    "AuctionAddress": "Auction address",
    "AuctionDescription": "Auction description",
    "AuctionDuration": "Auction duration",
    "Add": "Add",
    "Day": "Day",
    "Hour": "Hour",
    "Minute": "Minute",
    "Second": "Second",
    "YouCanAddImages": "You can add images",
    "YouCanAddVideo": "You can add video",
    "SubscribeInAuctionPackages": "Subscribe in auction packages",
    "EnjoyBiddingAndBuying": "Enjoy bidding and buying",
    "Packages": "Packages",
    "Pay": "Pay",
    "ForParticipationInAuctionYouMustSubscribeInOnePackage": "For participation in auction you must subscribe in one package"
  },
  "Addresses": {
    "Addresses": "Addresses",
    "AddAddress": "Add address",
    "AnyInstructionsToDriver": "Any instructions to driver",
    "AddressType": "Address type",
    "FlatNo": "Flat no",
    "NearestGuide": "Nearest guide",
    "SetAsDefault": "Set as default",
    "Delete": "Delete",
    "Edit": "Edit address",
    "ChooseAddress": "Choose address"
  },
  "CompleteOrder": {
    "RequiredMoney": "Required money",
    "WorkingOnSolveProblem": "Working on solving client problem",
    "ClientWillPay": "Client will pay required money when problem being solved",
    "Total": "Total",
    "ServiceCompleted": "Service completed",
    "SendRate": "Send rate",
    "SkipRate": "Skip rate",
    "Rate": "Rate",
    "RateClient": "Rate client"
  },
  "Setting": {
    "PrivacyAndPolicy": "Privacy & Policy",
    "QA": "FAQs",
    "Language": "Language (Arabic)",
    "SwitchToBusiness": "Switch to business",
    "NewMessage": "New message",
    "NewOrder": "New order",
    "NewReview": "New review",
    "Freelancer": "Freelancer",
    "Shop": "Shop",
    "ChooseTheTypeOfYourAccount": "Choose the type of your account",
    "Next": "Next",
    "BusinessAccount": "Business account",
    "WhatAreFieldsThatYouInterestingIn": "What are fields that you interesting in?",
    "Designing": "Designing",
    "Writing": "Writing",
    "Programming": "Programming",
    "ShopInformation": "Shop information",
    "ShopName": "Shop name",
    "BusinessRegister": "Business register",
    "Location": "Location"
  },
  "BankAccount": {
    "BankAccountInfo": "Bank account info",
    "UserName": "Account owner name",
    "BankName": "Bank name",
    "IbanNumber": "IBAN",
    "AccountNumber": "Account number",
    "CashOut": "Cash out"
  },
  "RequestProvider": {
    "Follow": "Follow",
    "RequestProvider": "Request provide",
    "ProblemLocation": "Problem location",
    "ProblemImages": "Problem images",
    "ProblemDesc": "Problem description",
    "SuitableCategory": "Suitable category"
  }
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar_SA": ar_SA, "en_US": en_US};
}
